version: "3.7"
services:
  app:
    image: stock-app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: stock-app
    volumes:
      - "./src/stock:/var/www"
    restart: always
    network_mode: host
  db:
    image: stock-db
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: stock-db
    volumes:
      - "./data/mysql:/var/lib/mysql"
    restart: always
    ports:
      - "8001:3306"