FROM mysql:5.7

ENV MYSQL_DATABASE: stock\
    MYSQL_ROOT_PASSWORD: root\
    MYSQL_PASSWORD: root\
    MYSQL_USER: admin

CMD [ "mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci" ]